print("calulation")
n1=float(input("input first number: "))
n2=float(input("enter second number: "))
print("addition: ",n1+n2)
print("subtraction: ",n1-n2)
print("multiplication: ",n1*n2)
print("division: ",n1/n2)
